default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: analyse_financiere_ia_development
  username: <%= ENV.fetch("DB_USERNAME", "cyrille") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>

test:
  <<: *default
  database: analyse_financiere_ia_test
  username: <%= ENV.fetch("DB_USERNAME", "cyrille") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
